# 站点基础信息
title: "你的博客名称"
description: "个人博客"
baseurl: ""
url: "https://hdbuyer.github.io"

# 语言和时区
lang: zh-CN
timezone: Asia/Shanghai

# 作者信息
author:
  name: "你的名字"
  avatar: "https://cdn4.winhlb.com/2025/10/01/68dc80e94e839.jpg" # 头像URL
  email: "your_email@example.com"
  bio: "个人简介/公司名"

# 导航栏
menu:
  - title: "首页"
    url: "/"
  - title: "分类"
    url: "/categories/"
  - title: "标签"
    url: "/tags/"
  - title: "归档"
    url: "/archives/"

# 社交分享（国内主流APP示例）
social:
  wechat: "微信ID"       # 点击可复制
  weibo: "微博ID"
  qq: "QQ号"

# 分类/标签
categories:
  - 工作
  - 生活
  - 情感

# 分页
paginate: 5
paginate_path: "/page:num"

# Markdown 解析
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# 插件
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap