# 网站基本信息
title: "您的公司名称"
description: "专业食品生产制造商，专注于健康美味食品"
baseurl: "" 
url: "https://您的用户名.github.io" 

# 主题设置（使用GitHub Pages支持的默认主题）
theme: jekyll-theme-cayman

# 联系信息
company_name: "您的公司名称"
address: "您的工厂地址"
phone: "您的联系电话"
email: "您的邮箱"

# 构建设置
markdown: kramdown
plugins:
  - jekyll-feed
