# 站点配置

# 导入主题
theme: jekyll-theme-chirpy

# 网页语言 › http://www.lingoes.net/en/translator/langcode.htm
# 如果名字与 `_data/locales` 中的文件同名，布局语言也会切换，否则使用默认 'zh-CN'
lang: zh-CN

# 时区设置 › https://kevinnovak.github.io/Time-Zone-Picker
timezone:

# jekyll-seo-tag 设置 › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: 王维便笺 # 站点主标题

tagline: 文字聚焦的 Jekyll 博客主题 # 站点副标题

description: >- # 用于 SEO meta 和 Atom feed
  一个简洁、响应式、功能丰富的 Jekyll 主题，适合技术写作。

# 填写站点协议 & 域名
# 例如 'https://username.github.io'，注意末尾不加 '/'
url: ""

github:
  username: hdbuyer # 你的 GitHub 用户名

twitter:
  username: "" # 你的 Twitter 用户名（可留空）

social:
  # 填写你的全名
  # 将作为文章默认作者及底部版权信息显示
  name: 王维
  email: "" # 你的邮箱地址
  links:
    # 第一个元素作为版权链接
    - https://github.com/hdbuyer
    # - https://twitter.com/username
    # - 可以添加更多社交链接
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

# 站点验证设置
webmaster_verifications:
  google: 
  bing: 
  alexa: 
  yandex: 
  baidu: 
  facebook: 

# ↑ --------------------------
# jekyll-seo-tag 设置结束

# 网站分析设置
analytics:
  google:
    id: 
  goatcounter:
    id: 
  umami:
    id: 
    domain: 
  matomo:
    id: 
    domain: 
  cloudflare:
    id: 
  fathom:
    id: 

# 页面浏览量设置
pageviews:
  provider: 

# 主题颜色偏好设置
# 保持为空将跟随系统默认颜色，并在侧边栏左下角提供切换按钮
# 可选值:
# light — 浅色主题
# dark — 深色主题
theme_mode: 

# 媒体资源 CDN 地址
cdn:

# 侧边栏头像，支持本地或 CORS 资源
avatar: https://cdn4.winhlb.com/2025/10/01/68dc80e94e839.jpg

# SEO 社交预览图片
social_preview_image: 

# 全局文章目录开关
toc: true

comments:
  provider: 
  disqus:
    shortname: 
  utterances:
    repo: 
    issue_term: 
  giscus:
    repo: 
    repo_id:
    category:
    category_id:
    mapping: 
    strict: 
    input_position: 
    lang: 
    reactions_enabled: 

# 自托管静态资源设置，可选 › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: 
    env: 

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:
      # - "/example"  # `<SITE_URL>/example/*` 不被 PWA 缓存

paginate: 10

# 站点基础路径
baseurl: ""

# ------------ 以下配置不建议修改 ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts: 
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/